info:
  component: zuul proxy

spring:
  application:
    name: proxy

server:
  port: 8000
  
zuul:
  routes:
    backend:
      path: /guestbook/**
      serviceId: backend
      strip-prefix: false
    frontend:
      path: /**
      serviceId: frontend
      
eureka:
  client:
    service-url:
#      defaultZone: http://discovery:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      management.port: ${management.port:8001}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
management:
  port: 8001
